"""Transactional todo-orchestrator v2 package."""

SCHEMA_VERSION = 2
PLAN_SCHEMA_VERSION = 3
SNAPSHOT_VERSION = 3
WORKFLOW_SNAPSHOT_VERSION = 1
RESPONSE_SCHEMA_VERSION = 2

__all__ = [
    "SCHEMA_VERSION", "PLAN_SCHEMA_VERSION", "SNAPSHOT_VERSION",
    "WORKFLOW_SNAPSHOT_VERSION", "RESPONSE_SCHEMA_VERSION",
]
